{
  "openapi": "3.0.3",
  "info": {
    "title": "SIXMATH API",
    "description": "API Spec for sixmath-app",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://sixmath.vnnyx.my.id/api"
    }
  ],
  "paths": {
    "/dashboard/statistik-pendaftaran": {
      "get": {
        "security": [
          {
            "SixmathAuth": []
          }
        ],
        "parameters": [
          {
            "name": "month",
            "required": true,
            "in": "query",
            "schema": {
              "type": "number"
            },
            "example": 3
          }
        ],
        "tags": ["Dashboard API"],
        "summary": "Get statistics",
        "responses": {
          "200": {
            "description": "Get statistics",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "month": {
                            "type": "string"
                          },
                          "amount": {
                            "type": "number"
                          }
                        }
                      }
                    },
                    "errors": {
                      "type": "object",
                      "nullable": true
                    }
                  }
                },
                "example":
                {
                  "code": 200,
                  "status": "OK",
                  "data": [
                    {
                      "month": "May",
                      "amount": 12
                    },
                    {
                      "month": "Apr",
                      "amount": 0
                    },
                    {
                      "month": "Mar",
                      "amount": 0
                    }
                  ],
                  "errors": null
                }
              }
            }
          }
        }
      }
    },
    "/video" : {
      "post": {
        "security": [
          {
            "SixmathAuth": []
          }
        ],
        "tags": ["Video API"],
        "summary": "Create new video",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "playlist_id": {
                    "type": "number"
                  },
                  "title": {
                    "type": "string"
                  },
                  "url_video": {
                    "type": "string"
                  },
                  "deskripsi": {
                    "type": "string"
                  }
                }
              },
              "example":
              {
                "playlist_id":1,
                "title":"video",
                "url_video":"youtube.video",
                "deskripsi":"this is a video"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success create video",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Video"
                    },
                    "errors": {
                      "type": "object",
                      "nullable": true
                    }
                  }
                },
                "example":
                {
                  "code": 200,
                  "status": "OK",
                  "data": {
                    "video_id": 1,
                    "playlist_id": 1,
                    "title": "video",
                    "url_video": "youtube.video",
                    "deskripsi": "this is a video"
                  },
                  "errors": null
                }
              }
            }
          }
        }
      },
      "get": {
        "security": [
          {
            "SixmathAuth": []
          }
        ],
        "tags": ["Video API"],
        "summary": "Get main video",
        "responses": {
          "200": {
            "description": "Success get main video",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Video"
                    },
                    "errors": {
                      "type": "object",
                      "nullable": false
                    }
                  }
                },
                "example":
                {
                  "code": 200,
                  "status": "OK",
                  "data": {
                    "video_id": 1,
                    "playlist_id": 1,
                    "title": "video",
                    "url_video": "youtube.video",
                    "deskripsi": "this is a video"
                  },
                  "errors": null
                }
              }
            }
          }
        }
      }
    },
    "/video/recommended": {
      "get": {
        "security": [
          {
            "SixmathAuth": []
          }
        ],
        "tags": ["Video API"],
        "summary": "Get recommended video",
        "responses": {
          "200": {
            "description": "Success get recommended video",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Video"
                      }
                    }
                  }
                },
                "example":
                {
                  "code": 200,
                  "status": "OK",
                  "data": {
                    "limit": 3,
                    "page": 1,
                    "sort": "rand()",
                    "total_rows": 2,
                    "total_pages": 1,
                    "rows": [
                      {
                        "video_id": 1,
                        "playlist_id": 1,
                        "title": "video1",
                        "url_video": "youtube.video1",
                        "deskripsi": "this is a video 1"
                      },
                      {
                        "video_id": 2,
                        "playlist_id": 1,
                        "title": "video2",
                        "url_video": "youtube.video2",
                        "deskripsi": "this is a video 2"
                      }
                    ]
                  },
                  "errors": null
                }
              }
            }
          }
        }
      }
    },
    "/user/student": {
      "post": {
        "tags": ["User API"],
        "summary": "Create student",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "handphone": {
                    "type": "string"
                  }
                }
              },
              "example":
              {
                "username":"myusername",
                "email":"myemail@email.com",
                "password":"password",
                "handphone":"081234567890"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Register user role student",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Student"
                    },
                    "errors": {
                      "type": "object",
                      "nullable": true
                    }
                  }
                },
                "example":
                {
                  "code": 200,
                  "status": "OK",
                  "data": {
                    "user_id": 1,
                    "email": "myemail@email.com",
                    "username": "myusername",
                    "handphone": "081234567890",
                    "created_at": "2022-05-18T15:20:32.135+07:00"
                  },
                  "errors": null
                }
              }
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["User API"],
        "summary": "User login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example":
              {
                "username":"myusername",
                "password":"password"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User Login",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number"
                    },
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "access_token": {
                          "type": "string"
                        },
                        "user_id": {
                          "type": "number"
                        },
                        "email": {
                          "type": "string"
                        },
                        "avatar": {
                          "type": "string"
                        },
                        "username": {
                          "type": "string"
                        }
                      }
                    },
                    "errors": {
                      "type": "object",
                      "nullable": false
                    }
                  }
                },
                "example":
                {
                  "code": 200,
                  "status": "OK",
                  "data": {
                    "access_token": "beaeretokenBEar3rTOK3nbeaeretokenBEar3rTOK3n",
                    "user_id": 1,
                    "email": "email@email.com",
                    "avatar": "https://res.cloudinary.com/avatar.jpg",
                    "username": "myusername"
                  },
                  "errors": null
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Video": {
        "type": "object",
        "properties": {
          "video_id": {
            "type": "number"
          },
          "playlist_id": {
            "type": "number"
          },
          "title": {
            "type": "string"
          },
          "url_video": {
            "type": "string"
          },
          "deskripsi": {
            "type": "string"
          }
        }
      },
      "Student": {
        "type": "object",
        "properties": {
          "user_id": {
            "type": "number"
          },
          "email": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "handphone": {
            "type": "string"
          },
          "created_at": {
            "type": "string",
            "format": "data-time"
          }
        }
      }
    },
    "securitySchemes": {
      "SixmathAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
